parameters:
    class_api_resource_loader: 'TCH\ApiResourceBundle\Routing\ApiResourceLoader'
    page_size: 10
    class_api_resource_pagination_factory: 'TCH\ApiResourceBundle\Factory\PaginationFactory'
services:
    tch.api_routing_loader:
        class: %class_api_resource_loader%
        arguments: [@service_container]
        tags:
            - { name: routing.loader }
    pagination_factory:
        class: %class_api_resource_pagination_factory%
        arguments: ['%page_size%']